version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - .db/data:/var/lib/postgresql/data
      - .db/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

  adminer:
    image: adminer
    restart: always
    ports:
      - 58080:8080
